### ISSUE TITLE
Samplingper

### ISSUE THREAD

**Issue by keuninkske** [SMFSW/CaptureTimer#3]
Hello,

I just tested your plugin
It does perfect what I need it to do, thanks for that
Can someone explain me what the variable samplingper in the example code does?
In one example it is set to 500
In another to 50
In the 3th I cannot find this variable

Thanks in advance

**Comment by SMFSW** [comment]
Hello,

Thanks, I'm glad this is useful to you!

[SimpleCapture.ino](https://github.com/SMFSW/CaptureTimer/blob/master/examples/SimpleCapture/SimpleCapture.ino)
The first 2 examples demonstrates how to capture a frequency of ticks in time windows.
Every tick appearing in the time window is counted. When the time window is over, frequency can be computed using number of ticks in the given time window.
The time window can be adjusted to your needs using `samplingPer` which refers to sampling period (in milliseconds).
Setting 50ms time window to capture an approximately 1Hz scale input wouldn't work for example; you would have to set it to a long time window for it to work (let's say at least 3000ms).

[TriggeredTickCapture.ino](https://github.com/SMFSW/CaptureTimer/blob/master/examples/TriggeredTickCapture/TriggeredTickCapture.ino)
In the last example, there is no need to set a time window as the purpose is to get the time between the moment you launch acquisition and the appearance of a tick.

I hope the explanations are clear enough to help understand how the lib works and what it can do.

**Comment by SMFSW** [comment]
Doxygen [docs](https://smfsw.github.io/CaptureTimer/) added
